services:
  sqli-nginx:
    image: nginx:stable-alpine
    container_name: sqli-nginx
    ports:
      - "80:80"
    volumes:
      - ${SQLI_NGINX_CONF_PATH}:/etc/nginx/conf.d/sqli.conf
      - ${SQLI_PATH}:/var/www/sqli:delegated
    restart: always
    networks:
      - sqli-net
    depends_on:
      - sqli-fpm

  sqli-fpm:
    image: sqli-fpm
    build:
      context: ./sqli-fpm
    volumes:
      - ${SQLI_PATH}:/var/www/sqli:delegated
      - ./secrets/flag.secret:/var/www/sqli/web/flag.secret:ro
    restart: always
    secrets:
      - mysql_pass
      - mysql_user
      - mysql_db
      - fe_flag
    environment:
      MYSQL_DB_FILE: /run/secrets/mysql_db
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_pass
      FE_FLAG_FILE: /run/secrets/fe_flag
    depends_on:
      - sqli-db
    networks:
      - sqli-net

  sqli-db:
    image: mysql:latest
    container_name: sqli-db
    restart: always
    ports:
      - "3316:3306"
    secrets:
      - mysql_pass
      - mysql_root_pass
      - mysql_user
      - mysql_db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
      MYSQL_DATABASE_FILE: /run/secrets/mysql_db
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_pass
    volumes:
      - ${SQLI_DATA_PATH}/db:/var/lib/mysql
      - ${SQLI_DATA_PATH}/db-dump:/docker-entrypoint-initdb.d
    command: --innodb-flush-method=fsync --log-bin=binlog --binlog-format=ROW  --local_infile=1
    networks:
      - sqli-net


networks:
  sqli-net:
    name: sqli-net
    driver: bridge

secrets:
  mysql_user:
    file: ./secrets/mysql_user.secret
  mysql_db:
    file: ./secrets/mysql_db.secret
  mysql_pass:
    file: ./secrets/mysql_pass.secret
  mysql_root_pass:
    file: ./secrets/mysql_root_pass.secret
  fe_flag:
    file: ./secrets/filter_evasion_flag.secret
